### ISSUE TITLE
Animation fix

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/electroncapture#12]
![ScreenRecorderProject5](https://user-images.githubusercontent.com/36500228/81218791-6e5c9500-8fe7-11ea-845a-d47049d9d34b.gif)

**Comment by steveseguin** [comment]
I've made some small improvements to this screen -- it no longer shows the QR code , but it may still have some animation problems.  I'll do some further testing to address this fully.

**Comment by steveseguin** [comment]
I've added an option in the upcoming release to completely disable this

**Comment by steveseguin** [comment]
I believe all these issues have slowly been fixed over the last couple months.

The error message only shows after like 20-seconds now, too, so quite a long time.

Closing.  Please open a new issue if problems remain.
