### ISSUE TITLE
Source video is blue screen when desktop app not top window on MacOS

### ISSUE THREAD

**Issue by kfsutton** [steveseguin/electroncapture#13]
When OBS.Ninja desktop application is covered by another application the source video turns blue in OBS window capture. When OBS.Ninja is selected as top window or moved to a second display (even if it is not the selected window, but is visible) it resolves the issue as long as another program window is not covering the OBS.Ninja application window.

Tested on OBS v23, v24, and v25.
MacOS Mojave 10.14.6

Video demonstrating issue attached.

[OBS Ninja Blue Screen Bug.mp4.zip](https://github.com/steveseguin/electroncapture/files/4698873/OBS.Ninja.Blue.Screen.Bug.mp4.zip)

**Comment by steveseguin** [comment]
OBS.Ninja as an app is always on top now. on both mac and windows.

If using Mac OBS, you can use "window" capture to avoid any further cover up, at the cost of added latency.
If using screen capture with window cropping, the always-on-top should be good enough in most cases.

If this problem still exists, please let me know and I'll reopen.
