### ISSUE TITLE
the right-click context menu gives an error if the main window is not active first

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/electroncapture#17]

**Comment by jcalado** [comment]
When is this supposed to happen? Launching the app and right clicking as my first interaction works as intended.

**Comment by steveseguin** [comment]
It works on Windows fine.

On Mac OS, this issue occurs if an Electron window is not actively selected. 

There is also a side problem, where if you have the wrong window selected, right clicking will affect the wrong window (the selected window - not the window you are right clicking)

I know where the problem is, though I haven't quite figured out the solution.
BrowserWindow.getFocusedWindow -> onclick -> no parent for the event.

I think I just need to try a few different methods of binding the parent window or getting the correct scope somehow.

Issue is also open here: https://github.com/sindresorhus/electron-context-menu/issues/42

perhaps related: https://github.com/sindresorhus/electron-context-menu/issues/30

**Comment by chrismarquardt** [comment]
I see the same behavior. No error message when OBSN already has focus, yes error message when it doesn't have focus.

OBSN's startup behavior on macOS seems to be that OBSN has focus while starting up, then the focus goes back to whatever was app was focused before. 

Several ways of running OBSN: 
A) double click from Finder
B) start OBSN from Spotlight search
C) start OBSN.app from Terminal (open /Applications/OBSN.app)

In all three cases, after OBSN has finished starting, focus goes back to whatever other app was focused before.

Other GUI apps stay focused after starting up.

**Comment by jcalado** [comment]
Can anyone elaborate on steps to reproduce?
Because running from source I can't reproduce.
Neither after building the app and running the app.

**Comment by steveseguin** [comment]
Are you on mac OS?

**Comment by jcalado** [comment]
Yup running on a VM.
