### ISSUE TITLE
Have the app change the window size based on the video resolution

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/electroncapture#2]
This dynamic resolution changing behaviour might be a security concern, but mainly is just a hassle to setup.

it does make sense to do though.

By default though, 1280x720 seems to make sense.

**Comment by steveseguin** [comment]
If I can tell the app is playing a video, maybe I can get the app to tell MacOS to hide the cursor??

**Comment by steveseguin** [comment]
Can I tell it to also "be on top" of other apps?

**Comment by steveseguin** [comment]
I give the user control to manually size the window now; context menu or via URL.  It is also on top.  I am not going to let it be dynamic in size, as that will potentially cause more problems

**Comment by scalpmonkey** [comment]
Perfect! I have some more suggestions. Should I explain them in new, separate issues?
tnx!

**Comment by steveseguin** [comment]
new issues are less likely to get lost
