### ISSUE TITLE
'Attempting to load video stream' error

### ISSUE THREAD

**Issue by INDIGI-CO-UK** [steveseguin/electroncapture#28]
I can't get stream on remote OBS. I can get the stream only in my local network. When I'm sending my link from ops.ninja to my friend, he can't get feed. In OBSN he have only "Attempting to load video stream. The stream is not available yet or an error occurred."

How to solve that problem?

**Comment by steveseguin** [comment]
Are you on Virgin Mobile internet?

Are you using a VPN or is your friend using a VPN? Have you tried turning it off?

Is your friend on a Mac system?

Does the stream appear in Chrome for you or your friend? Does it only not work in OBS?  

Have you turned on Browser Source Hardware Acceleration in OBS? (advanced settings)  Have you tried with it on and off?
