### ISSUE TITLE
[OBSN] not showing in OBS Display Capture

### ISSUE THREAD

**Issue by sirjonathan** [steveseguin/electroncapture#32]
I've just downloaded and installed OBSN and am running the latest version of OBS (26.0). When I go to "Display Capture" and choose "Window", [OBSN] doesn't show up (see screenshot).

I've done a fresh reboot of the computer to see if it was just an issue with OBS. 

![image](https://user-images.githubusercontent.com/104149/94723595-d650a680-030d-11eb-99cd-8ac53137398b.png)

Any ideas?

**Comment by steveseguin** [comment]
I appreciate that issue report. I'll check it out shortly

**Comment by steveseguin** [comment]
How many Displays do you have? is it on a different display by chance?

**Comment by steveseguin** [comment]
```I remember reading in the release notes that they removed unnecessary windows from the list.```

Seems like OBS v26 broke this feature.  I'll have to find a way to get it working again.

**Comment by steveseguin** [comment]
https://github.com/obsproject/obs-studio/issues/3528

**Comment by steveseguin** [comment]
it should look like this I guess:
![image](https://user-images.githubusercontent.com/2575698/94749177-33218080-0351-11eb-8a4a-d45bc50539d9.png)

OBSN X

This has also broken: https://github.com/steveseguin/s10capture/

**Comment by sirjonathan** [comment]
Thank you for the quick response @steveseguin! I've got two displays. I checked both several times, just to be sure.

**Comment by steveseguin** [comment]
So the solution for now is to disable the "Always on Top" feature of the Electron Capture app, but only just when you need to select it in OBS.  After you select the window in OBS, you can re-enable the always-on-top function.

Right click on the Electron Capture app to have an option to enable/disable it.

![image](https://user-images.githubusercontent.com/2575698/94753213-8bf61680-035b-11eb-8beb-8c6fd5f74a13.png)

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/94757369-10e72d00-0368-11eb-98b3-a4a29c43dc09.png)

I update the electron code to reflect this requierment

**Comment by steveseguin** [comment]
i'll be removing this message in the near future, since OBS v26.2 or whatever no longer has this issue
