### ISSUE TITLE
Screen share isn't supported yet 

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/electroncapture#34]

**Comment by steveseguin** [comment]
https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md

`jcaladoToday at 10:31 AM
steve, latest electron looks like fun for you
Added desktopCapturer.getMediaSourceIdForWebContents(), can be used with getUserMedia to get a stream for a WebContent. #22701`

**Comment by shoei101** [comment]
i haven't been able to get "Screen Share with Room" to work using the electron app v1.1.3 (hoping i would be able to share audio from an application). Is this still an issue or am i doing something wrong?  I've tried on High Sierra, Catalina and Big Sur and it all acts the same.  i go to press "select screen to share" and nothing happens.

**Comment by steveseguin** [comment]
Hi @shoei101   This is still a missing feature of the electron app, sadly.  We made some progress on it, but there is still lots to do.  If it's something that's urgent to you, I can try to prioritize it.

**Comment by shoei101** [comment]
Hello good sir!  i'm sure you have a lot more pressing matters and i'm able to get it to work using a PC (obviously), i just wanted to make sure that i wasn't missing anything or doing something wrong. thank you for you time and hard work!

**Comment by steveseguin** [comment]
Added to 1.5.0 of the app, but it only works with v17 of OBS.NInja (on alpha atm)
