### ISSUE TITLE
Consider Linux support too

### ISSUE THREAD

**Issue by olberger** [steveseguin/electroncapture#53]
I must say I haven't tested rebuilding on Linux at all, but it seems that the README more or less mentions "you're on your own" regardiing Linux ;-)

In principle, this is totally fine, but I'd like to draw your attention to the fact that the browser plugin for OBS isn't available in most distros (see https://github.com/steveseguin/obsninja/issues/781).

IIUC, this offers an alternative, so it might be useful to improve Linux support, or at least try to focus a bit less on "this is for MacOS users".

Of course I may be mistaken, and I hope to be able to contribute bits of docs or other supporting help.

Best regards,

**Comment by steveseguin** [comment]
Thank you.  It's a fair point; Linux users would benefit from greater support.  Most Linux users I know are quite technical and are familiar with compiling software.  I'm a bit stuck though with trying to offer better support for them though as there are so many different distros out there, and they all seem to have different workflows and gotchas.

The mentions of macOS are mostly just lingering outdated comments.  I do need to go thru and clean things up a bit. 

Thank you

**Comment by olberger** [comment]
An intermediate way to improve Linux support could be to provide a Docker container for one distro, and make that runable fo others, or snaps and other way to run a containerized app... but that probably has issues too.

I think Electron-based apps like Teams or Zoom or others (IIUC) aren't easy to package.

Maybe smarter people will offer better insight ;-)

**Comment by steveseguin** [comment]
Thankfully it is just a simple electron app, and there's been at least 3 linux users who have confirmed they have it working. None have mentioned issues with installing, so I presume it's pretty straight forward.  

My preference will be to support 1 or 2 common distros, by offering step-by-step compiling instructions.  Shouldn't be more than 5 lines.  I think Ubuntu is an easy choice there.  As mentioned, I welcome input from other linux users as to how best to support them.

**Comment by jcalado** [comment]
If you have an healthy nodejs environment:

1) git clone https://github.com/steveseguin/electroncapture.git
2) cd electroncapture
3) npm install
4) npm run build:linux

You now have an appImage inside `dist/`

**Comment by olberger** [comment]
I've tested this (now in the README, thx), and it works.

Will report of further issues.
