### ISSUE TITLE
Not only receiving, but also sending

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/electroncapture#6]
For convenience and reliability, use the application itself, and not the tab in the browser, to use OBS.Ninja to send video from the camera or to display the screen.
![image](https://user-images.githubusercontent.com/36500228/80235947-0ad77c80-8663-11ea-86f9-c09f46fde1d4.png)

**Comment by steveseguin** [comment]
I can definitely do that, thank you.  It would probably be more reliable in the long run.

**Comment by steveseguin** [comment]
Just a status update:

So currently you can do this just by visiting https://obs.ninja when opening the electron app.  It works okay, although there are some potentially issues with the header area that might prevent mouse clicks.  There are a few reasons why I might want to do this, such as having GPU-encoding, better audio/video sync, or experimental flags enabled, although it hasn't been enough of a problem yet. 

![image](https://user-images.githubusercontent.com/2575698/92179928-c7143100-ee13-11ea-94a6-d83dad96c048.png)

I definitely do want to offer a version with GPU encoding at some point, so I'll leave this task open, as it will be part of that task.

**Comment by steveseguin** [comment]
screen share works in the newest version with v17 of OBSN.
