### ISSUE TITLE
No 32bit Build?

### ISSUE THREAD

**Issue by NoobArpan** [steveseguin/electroncapture#60]

**Comment by steveseguin** [comment]
Can you please test this release out?  I think I added 32 bit support, but I can't really test easily.

https://github.com/steveseguin/electroncapture/releases/tag/2.1.3

**Comment by NoobArpan** [comment]
Worked. It's a big boy. 100mb

**Comment by steveseguin** [comment]
it's both the 64 and 32 bit versions, combined.  Glad it works!
