### ISSUE TITLE
Facebook video clean output

### ISSUE THREAD

**Issue by floyd168** [steveseguin/electroncapture#69]
Is there a way to clean Facebook video output with fixed size?
This clean video option is only available on YT now . Thank you

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.11.0
done.  It was supported before with twitch and youtube, but now it should work with most sites that have a video

**Comment by floyd168** [comment]
> https://github.com/steveseguin/electroncapture/releases/tag/2.11.0 done. It was supported before with twitch and youtube, but now it should work with most sites that have a video

Thank you so much for your speedy reply. It works perfect for me!

**Comment by floyd168** [comment]
> https://github.com/steveseguin/electroncapture/releases/tag/2.11.0 done. It was supported before with twitch and youtube, but now it should work with most sites that have a video

Thank you so much for your speedy reply，Ít works perfect for me!
