### ISSUE TITLE
Not an Issue but support Request?

### ISSUE THREAD

**Issue by TecWiz12** [steveseguin/electroncapture#70]
Ability to use or access Chrome extensions like 
FFZ - https://www.frankerfacez.com/
BTTV - https://betterttv.com/
7TV - https://7tv.app/ 

use case or reason, I use your amazing software for other unexpected uses, where i load Twitch in them as either embedded windows, or to access mod view in a more "windowed" version of the channel, this allows that page to have a more fenced out look, the use for me personally ffz is a great option to add extra things to the twitch experience.

**Comment by steveseguin** [comment]
Thank you for the request.  I've been thinking about doing this, although not sure how easy it will be to do.  I'll give it a shot though; if easy, I'll add it in.

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.15.0

**Comment by TecWiz12** [comment]
Installing now will provide feedback once and test it out more for ya thank you so much for the quick turn around
