### ISSUE TITLE
Feature Request: Loading custom .CSS file via command line

### ISSUE THREAD

**Issue by E2Gabriel** [steveseguin/electroncapture#72]
This would be a huge help in cases where users have already decided on alternate CSS and want to automate the process of loading custom stylesheets when launching Electron Capture.

(Thanks for the awesome tool, by the way!)

**Comment by steveseguin** [comment]
Would you want the CSS being loaded into every page? or just the initial page being loaded via URL?

**Comment by steveseguin** [comment]
If loading VDO.Ninja, you can specify a CSS script via the VDO.Ninja URL.

I guess also, is this a local CSS script or a remote web hosted css script? OR is this base64?

**Comment by E2Gabriel** [comment]
Simply loading the initial target URL with custom CSS would work fine in my particular use case.
The CSS script I would use, in my case, is local. The way I would want to use it would be something like:
ElectronCapture.exe --u 'website.html' --css 'path\custom CSS.css'

**Comment by steveseguin** [comment]
I got it added.

https://github.com/steveseguin/electroncapture/releases/tag/2.70.0

I'll include a mac release soon as well.

I think it will work if it's in the same directory as the css file or if you provide the absolute path

`elecap --css test.css`
