### ISSUE TITLE
Parameter Request: start minimized

### ISSUE THREAD

**Issue by XIIIG** [steveseguin/electroncapture#73]
Hello,

Would be neat if we could run electron window minimized.

I've tried to use .bat file with `start /min`, but no luck - electron window stays on screen.

I would appreciate --minimized parameter.

**Comment by steveseguin** [comment]
Thank you for the request and sorry for the delay:

I've added this feature request to the pre-release version here:
https://github.com/steveseguin/electroncapture/releases/tag/2.70.0

--minimized I think should so it
