### ISSUE TITLE
rtmp support

### ISSUE THREAD

**Issue by qian-jiang** [steveseguin/electroncapture#78]
Whether to support push flow to rtmp server

**Comment by steveseguin** [comment]
Thank you for the request.

I've been meaning to get around to that, but it will be a few solid days of work and haven't prioritized it yet, mainly given how OBS or other apps can do it currently.

I think Vingester.app can currently do it also, https://github.com/steveseguin/vingester/releases/tag/2.8.1 via the FFMPEG option it has. 

There's also a docker container, https://github.com/steveseguin/browser-to-rtmp-docker, which can be deployed to do it as well. 

But still, thank you -- I do intend to get this support added, as I would like to continue to develop and expand Electron Capture with such features.

**Comment by qian-jiang** [comment]
Thank you for your reply

> Thank you for the request.
> 
> I've been meaning to get around to that, but it will be a few solid days of work and haven't prioritized it yet, mainly given how OBS or other apps can do it currently.
> 
> I think Vingester.app can currently do it also, https://github.com/steveseguin/vingester/releases/tag/2.8.1 via the FFMPEG option it has.
> 
> There's also a docker container, https://github.com/steveseguin/browser-to-rtmp-docker, which can be deployed to do it as well.
> 
> But still, thank you -- I do intend to get this support added, as I would like to continue to develop and expand Electron Capture with such features.

Thank you for your reply
