### ISSUE TITLE
Stop window resize when editing URL

### ISSUE THREAD

**Issue by scalpmonkey** [steveseguin/electroncapture#83]
Any way the window stays same (full screen in my case) when editing to new URL on Win 10?

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.17.7

I updated the code to try to accommodate. Please let me know you have issues.

**Comment by scalpmonkey** [comment]
Hi,
the window now does not resize, but it moves to the Primary monitor/display. It should stay to the monitor where it it at the moment of editing the url.

**Comment by steveseguin** [comment]
ah, sorry.  I wasn't moving for me, but thank you for the update; i'll try to fix it again.

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.17.8

try #2  Thank you

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.17.9
there might have been a bug in my last version, wrt to this feature
