### ISSUE TITLE
Please add Fullscreen shortcut

### ISSUE THREAD

**Issue by scalpmonkey** [steveseguin/electroncapture#86]
Can we please have shortcut for fast maximizing to full screen?
Thanks!

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.17.9
added ALT+TAB to full screen

**Comment by scalpmonkey** [comment]
alt+tab opens the application switcher. But I guess what you mean is alt+enter? Correct? :)
G

**Comment by steveseguin** [comment]
alt enter. yes., ddohh.
