### ISSUE TITLE
Auto add https:// to urls

### ISSUE THREAD

**Issue by scalpmonkey** [steveseguin/electroncapture#88]
Hi,
please make it possible that youtube.com automatically resolve to https://youtube.com
Its not a big deal but typing it all over again gets annoying.

Thanks

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/releases/tag/2.17.9
I think I have that fixed now

**Comment by scalpmonkey** [comment]
Correct! Fixed!
