### ISSUE TITLE
Is it possible to mute window from start? 

### ISSUE THREAD

**Issue by katoquro** [steveseguin/electroncapture#94]
I run ElectronCapture from the command line to open a window with the exact size and URL. However, when I run the link with a solo view I have to mute it to not hear me twice (parallel to monitor sound). Can I mute it from the very beginning with something CLI parameter (I didn't find a corresponding)?
Thanks for the great app.

**Comment by steveseguin** [comment]
I don't have an Electron Capture specific command line option to cause a window to be loaded by default in a muted state.  It's possible I could add it and release an updated binary with that change.

Alternatively

&volume or &speakermute on the view link might allow you to unmute it via vdo.ninja.  The video control bar can be made visible via URL parameter also, or holding CTRL, right click the video, show controls, and then un-mute.  You can also press ALT + A , with the window in focus, to trigger video to toggle the speaker mute on and off without the control bar being visible.

You can also add &noaudio to disable audio entirely for that view link.

**Comment by katoquro** [comment]
Thanks for the swift response. 
Looks like `&noaudio` is what I need. Am I right that will not affect my co-host because they hear me via the vdoninja directly?

**Comment by steveseguin** [comment]
&noaudio will not impact outgoing audio.  It will just tell remote peers not to send that specific page audio tracks, saving bandwidth, so its better than muting if you don't need to unmute.
