### ISSUE TITLE
Request for an up-to-date pre-built Linux binary (AppImage)

### ISSUE THREAD

**Issue by krt222** [steveseguin/electroncapture#97]
I would like to request an up-to-date pre-built Linux binary (AppImage).

The last binary was built back in 2021 (version 2.5.0). npm can be pretty much "hell" in certain environments and docker is often an overkill in terms of resources.

Thank you very much!

**Comment by steveseguin** [comment]
Thank you for the request.

I tried setting something up here to auto-build Linux App images, which will get auto-built and listed in the actions page I think: https://github.com/steveseguin/electroncapture/actions

A download link to the newest build is here, however I'll preface by saying I haven't tested it yet --  https://github.com/steveseguin/electroncapture/actions/runs/9150314190/artifacts/1517455678

I'm not super experienced with creating auto-building Github actions, so if anyone wanted to update the current Github action to include Windows + Mac , and auto create a release, that would be quite useful I'd think.

**Comment by krt222** [comment]
Thank you for the prompt response!

The new version seems to work as expected for my usual workflow. The terminal log is "chattier" than the previous pre-built binary but I think I prefer it this way.

Thank you again!

PS: I am closing the issue, but I agree that an auto-build workflow through Github actions would be quite useful.
